import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AudioPlayerProvider } from "@/contexts/AudioPlayerContext";
import { ThemeProvider } from "@/contexts/ThemeContext";
import { SearchProvider } from "@/contexts/SearchContext";
import { QueryProvider } from "@/providers/QueryProvider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <SearchProvider>
            <ThemeProvider>
              <AudioPlayerProvider>{children}</AudioPlayerProvider>
            </ThemeProvider>
          </SearchProvider>
        </QueryProvider>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              if (typeof window !== 'undefined') {
                window.addEventListener('load', () => {
                  const perfData = performance.getEntriesByType('navigation')[0];
                  console.log('[Perf] Page load metrics:', {
                    ttfb: Math.round(perfData.responseStart - perfData.requestStart),
                    fcp: Math.round(perfData.domContentLoadedEventEnd - perfData.fetchStart),
                    load: Math.round(perfData.loadEventEnd - perfData.fetchStart),
                  });
                });
              }
            `,
          }}
        />
      </body>
    </html>
  );
}
